### ISSUE TITLE
SDGCN model

### ISSUE THREAD

**Issue by yassmine-lam** [BinLiang-NLP/Sentic-GCN#3]
Hi,

First, thank u for sharing this great work with us.

I have a question about this model sdgcn.py is this an implementation of this paper "Modeling Sentiment Dependencies with Graph Convolutional Networks for Aspect-level Sentiment Classification" If no could u please provide a description of this model?

Many thanks in advance.

**Comment by BinLiang-NLP** [comment]
> Hi,
> 
> First, thank u for sharing this great work with us.
> 
> I have a question about this model sdgcn.py is this an implementation of this paper "Modeling Sentiment Dependencies with Graph Convolutional Networks for Aspect-level Sentiment Classification" If no could u please provide a description of this model?
> 
> Many thanks in advance.

Hi,
Thanks for your question.
I apologize for the confusion. The model **sdgcn.py** is not for the paper "Modeling Sentiment Dependencies with Graph Convolutional Networks for Aspect-level Sentiment Classification". **sdgcn.py** is one of the variants of our model, which interactively performs the graph convolutional operation based on dependency (i.e. Eq. 1) and affective (i.e. Eq.2) graphs.
We also provide several variants of our model. Please see the [README](/README.md#see-also).

**Comment by BinLiang-NLP** [comment]
> > Hi,
> > First, thank u for sharing this great work with us.
> > I have a question about this model sdgcn.py is this an implementation of this paper "Modeling Sentiment Dependencies with Graph Convolutional Networks for Aspect-level Sentiment Classification" If no could u please provide a description of this model?
> > Many thanks in advance.
> 
> Hi, Thanks for your question. I apologize for the confusion. The model **sdgcn.py** is not for the paper "Modeling Sentiment Dependencies with Graph Convolutional Networks for Aspect-level Sentiment Classification". **sdgcn.py** is one of the variants of our model, which interactively performs the graph convolutional operation based on dependency (i.e. Eq. 1) and affective (i.e. Eq.2) graphs. We also provide several variants of our model. Please see the [README](https://github.com/BinLiang-NLP/Sentic-GCN/blob/main/README.md#see-also).

**Comment by yassmine-lam** [comment]
Ok I see. Thank u very much for ur quick reply!
